[package]
name = "ailocker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
opencv = "0.98.1"
ndarray = "0.17.2"
ort = { version = "2.0.0-rc.11", features = ["cuda", "download-binaries"] }